### ISSUE TITLE
Sales Recap and TMP

### ISSUE THREAD

**Issue by TinaGriffin** [Fujitsu-America/Fujitsu-Repository#28] opened 2021-06-04 20:05 UTC
**Describe the bug**
In HTML Quoting, in order to process a quote we have two custom links called "Sales Recap" and "TMP".  These buttons are not opening their appropriate forms and without them we cannot enter quotes as they are a huge part of our business.

**Instance Name**
Instance: TPQS2I

**Responsibility Name**
Responsibility: PBS US Contract Administrator (or PBS CAN Contract Administrator)

**Navigation**
Navigation: PBS US Contract Administrator / HTML Quote Administration / Quotes / Dashboard

**To Reproduce**
1. Go to 'Simple Search'
2. Click on 'Quote Number' enter 198146
3. Click 'Go'
4. Click on Quote Name to Open
5. Click on 'Sales Recap' button on top of screen

**Expected behavior**
Normally the Sales Recap page would open, you would enter the term there, SAVE. Then Click on the TMP Button and SAVE
[STG Issue Sales Recap and TMP Buttons not opening.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6601009/STG.Issue.Sales.Recap.and.TMP.Buttons.not.opening.docx)
.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vinaytalasila** [comment] 2021-06-04 20:37
Tina,

I reproduced this issue in Chrome browser and I am getting the below error. We will work on this on Monday and keep you posted.

![image](https://user-images.githubusercontent.com/84878630/120859870-72404b00-c54a-11eb-9c81-05fa191a82a9.png)

@amitjori @SomuSundaramM : Could you please check whether any services are down in STG 12.2.10 or any instance bounce is required for this issue.

Thanks
Vinay Talasila

**Comment by vinaytalasila** [comment] 2021-06-07 21:42
Just an update...OAF forms personalizations in the path /oracle/apps/pbs/quote/header/webui/XXSalesRecapPG are missing in STG 12.2.10 instance. DBA Team will bring over all the personalizations in that path from 12.1.3 instance to STG 12.2.10. After that we will retest the issue and keep you posted.

Thanks
Vinay Talasila

**Comment by amitjori** [comment] 2021-06-08 07:50
Hi Team,

pbs folder copied from SOURCE (Prod) to STG and INT 12.2.10 instance under $JAVA_TOP/oracle/apps 

Custdocs folder created on source.

INT and STG application services restarted.

[apppqs1i@sbsashpebsap1 tmp]$ hostname -f
sbsashpebsap1.oci.snapbs.com
[apppqs1i@sbsashpebsap1 tmp]$ cd custdocs/
[apppqs1i@sbsashpebsap1 custdocs]$ pwd
/tmp/custdocs

Regards,
Amit

**Comment by ashoksnapfj** [comment] 2021-06-09 13:48
Hi Tina,

This issue is fixed now. I have attached the file after I tested in STG.
Please test and provide us your feedback.

Thanks
Ashok.T
[STG.Issue.Sales.Recap.and.TMP.Buttons.working.docx](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6624201/STG.Issue.Sales.Recap.and.TMP.Buttons.working.docx)

**Comment by TinaGriffin** [comment] 2021-06-09 17:02
I've retested this and the issue is resolved.  This can be closed.

**Comment by vinaytalasila** [comment] 2021-06-09 21:32
**@amitjori and @SomuSundaramM :** Could you please recollect the processes or setups that you applied yesterday (6/8/2021) in STG 12.2.10 and list them out here so that we can close this ticket. Because of those setups, this issue was fixed. Also, move those setups to INT 12.2.10 instance. 

Thanks
Vinay Talasila

**Comment by amitjori** [comment] 2021-06-10 10:07
Hello Vinay, 
Below steps were performed in STG 12.2.10 while troubleshooting the global licensing  issue which seems to have resolved this issue, we have performed these steps in INT 12.2.10 instance. you may please test the issue in INT 12.2.10 instance.

perform below on both private and public tier 
1) pbs folder copied from SOURCE (Prod) to  INT 12.2.10 under $JAVA_TOP/oracle/apps
2) cd $JAVA_TOP
3) zip -r custompbs.zip $JAVA_TOP/oracle/apps/pbs

3) adjava oracle.apps.ad.jri.adjmx -areas $JAVA_TOP/custompbs.zip -outputFile $JAVA_TOP/custompbs.jar -jar $CONTEXT_NAME 1 CUST jarsigner

4) cd $FND_TOP/admin/template
5) mkdir custom
cd custom/
cp -rp /oci-backup/ebsProductManifest_xml.tmp .
cd $JAVA_TOP
6) [apdpqs2i@isbsashebsap4 classes]$ adcgnjar

7) Using adadmin utility generate message ,form,reports and JAR files

   1.    Generate message files

   2.    Generate form files

   3.    Generate report files

   4.    Generate product JAR files

run autoconfig on public and private tier
startup services on private and public tier

Regards,
Amit

**Comment by vinaytalasila** [comment] 2021-06-10 12:47
Thank you Amit. 

Tina,

Before we close this issue, could you please test this in INT 12.2.10 instance as well?

Thanks
Vinay Talasila

**Comment by TinaGriffin** [comment] 2021-06-10 13:14
I've tested in INT 12.2.10.  At first I got the Error Page error as is above in this ticket when trying to open the quote altogether.  But I tried it a second and third time and the third time it worked, so I'm not sure if something else was happening at first.  But this issue is fixed in INT and can be closed.

**Comment by vinaytalasila** [comment] 2021-06-10 13:24
Thank you for your update Tina.

**Closed as completed by vinaytalasila** 2021-06-10 13:24 UTC
Labels: Show stopper
