### ISSUE TITLE
12.2.10 Sales Manager Dashboard -SR 3-26270330931

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#57] opened 2021-06-17 19:00 UTC
The sales manager dashboard in 12.2.10 is not the same sales manager dashboard as 12.1.3.  They do not display the same information.

![sales manager dashboard 12 1 3](https://user-images.githubusercontent.com/85238444/122457427-a2411280-cf7c-11eb-9900-9ef7d1556dc1.jpg)
![sales manager dashboard 12 2 10](https://user-images.githubusercontent.com/85238444/122457445-a705c680-cf7c-11eb-9070-d6370c9d4e28.jpg)

**Comment by lindamrigo** [comment] 2021-06-17 19:00
first screen shot is 12.1.3
second screen shot is 12.2.10
Same user

**Comment by Haqueraz** [comment] 2021-06-17 19:56
Hi Linda, 
We already aware about this page . Oracle has changed this page in R12.2.10 upgrade version. 

Let us know if you have any queries. 

Thanks 
Razaul

**Comment by lindamrigo** [comment] 2021-06-17 20:02
What is the replacement page? The page currently displaying does not display any dashboard information.

**Comment by lindamrigo** [comment] 2021-06-17 20:02
The current page is not a dashboard. It is linked list page

**Comment by Haqueraz** [comment] 2021-06-17 20:13
We will check and let you know. 

@amitjori @AkshayK247  Can you please check ,Is there is any way to  display any dashboard information.

Thanks
Razaul

**Comment by ashoksnapfj** [comment] 2021-06-29 13:18
============== below is update from oracle ==========
Hi Ashok,

I could see the same behavior in internal instances.
Looks like Sales Manager Dashboard belongs to Oracle Sales Intelligence which is related to DBI and it is discontinued from 12.2.

I have mailed to Sales Dev about the difference in 12.2. Will confirm you as soon as i hear from them.


Regards,
Vignesh 
=================================

**Comment by SherryXLiu** [comment] 2021-06-30 15:10
@lindamrigo @vinaytalasila 
Garnett has confirmed that they DO NOT need those charts/dashboard. The Sales Manager (12.2.10) page is OK without them

**Comment by Haqueraz** [comment] 2021-07-01 14:41
Thank Sherry for the confirmation. I am closing this issue. 

No action required. User are agree to go with new standard page.

**Closed as completed by Haqueraz** 2021-07-01 14:41 UTC
Labels: Medium
