### ISSUE TITLE
INT PBS GL Create Initial JE Errors

### ISSUE THREAD

**Issue by lindamrigo** [Fujitsu-America/Fujitsu-Repository#58] opened 2021-06-17 19:35 UTC
Liz Fulton ran the PBS GL Amortization Schedule program and that finished fine and should have created new amortization schedules that would be picked up on the PBS GL Create Initial JE’s.
![Create Initial JE](https://user-images.githubusercontent.com/85238444/122461448-5e044100-cf81-11eb-9910-6b019e96b5d6.jpg)
[PBS GL Create Initial JE's Error.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6672803/PBS.GL.Create.Initial.JE.s.Error.txt)

**Comment by Haqueraz** [comment] 2021-06-17 22:25
Hi Linda, 
We have fixed this issue in INT Instance. 

Custom table pbs_gl_initial_je have a  unique contract on column contract ID. 

I have put the exception so program will complete with Normal status. 

Thanks 
Razaul

**Comment by Haqueraz** [comment] 2021-06-17 22:44
![image](https://user-images.githubusercontent.com/84917836/122481028-96ad1600-cf93-11eb-88ae-a8d1edf6885c.png)

**Comment by Haqueraz** [comment] 2021-06-18 15:01
Hi Sherry , 
As discussed in in daily status call please find the attached updated scripts. 
![image](https://user-images.githubusercontent.com/84917836/122580883-0ebf1e80-d01c-11eb-9dba-9b1bed75c0a7.png)


[pbs_gl_amort_cust_je_pkg.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6677824/pbs_gl_amort_cust_je_pkg.txt)

**Comment by SherryXLiu** [comment] 2021-06-18 19:01
Please indicate the line number of the code. Thanks

**Comment by Haqueraz** [comment] 2021-06-18 19:22
Please see the line # between 2970 to 2977 in the attached scripts .

![image](https://user-images.githubusercontent.com/84917836/122607634-7e470500-d040-11eb-99e5-b4cebbdfc365.png)

**Comment by SherryXLiu** [comment] 2021-06-18 19:39
The process showed an error, the cause was a TMP journal entry had not completed. I will close this issue, next time please do not change SBS program to fix none upgrade issues.
Thanks

**Closed as completed by SherryXLiu** 2021-06-18 19:39 UTC
Labels: Medium
