### ISSUE TITLE
STG 12.2.10 IB Issue from the Service Request Form

### ISSUE THREAD

**Issue by vinaytalasila** [Fujitsu-America/Fujitsu-Repository#19] opened 2021-06-02 19:10 UTC
**Describe the bug**
Here is the error when trying to add an Install Base Instance on a Service Request in the PBS Automotive Customer Support Responsibility.  This only seems to occur on existing Service Requests and does not throw the error if you create a new service request.

**Instance Name**
Instance: STG 12.2.10

**Responsibility Name**
Responsibility: PBS Automotive Customer Support 

**Navigation**
Navigation:

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/84878630/120538344-03c58680-c3ac-11eb-8fe3-2132cb7c20df.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Haqueraz** [comment] 2021-06-03 22:33
This Issue has been fixed in both Instance INT &STG 
We prepared the data fixed to update business process .

Please verify the same and let us know if you have any question.

**Comment by TinaGriffin** [comment] 2021-06-04 12:17
I've retested this in STG.  The issue is resolved and can now be closed.
Thank you.
Please provide a high level of what the fix was before closing the issue.

**Comment by Haqueraz** [comment] 2021-06-04 12:59
I have attached the update scripts. 
[PBS_UPD_CS_INCIDENTS_ALL_B.txt](https://github.com/Fujitsu-America/Fujitsu-Repository/files/6598633/PBS_UPD_CS_INCIDENTS_ALL_B.txt)

**Closed as completed** 2021-06-04 13:02 UTC
Labels: Medium
